### ISSUE TITLE
Manual Entry of Min/Max X- and Y- axis values doesn't not always adjust the Plot View as requested

### ISSUE THREAD

**Issue by vasangithub** [VirtualPhotonics/Vts.Gui.Wpf#45] opened 2023-12-06 20:40 UTC
**Describe the bug**
Often when generating reflectance vs rho or time or spatial frequency, the minimum y-axis tick mark is not at 0 but located close to the minimum y value. De-selection of the Auto-X/Auto-Y feature and manual entry of Min/Max X and Y values does not allow expansion of the graph so that we can clearly visualize the origine. The manual entry of Min/Max x- and y- axis values should be fully functional independent of the values of the data point to allow customized zooming in (or out) of the data as desired by the user. I would like to generate a plot where the lower left hand corner represents the origin i.e., x=0, y=0.

**To Reproduce**
See screenshot below. Y-Axis cannot be rescaled so that the y-axis spans from 0 to 0.5.

**Expected behavior**
Y-axis range should adjust based on user input

**Screenshots**
![image](https://github.com/VirtualPhotonics/Vts.Gui.Wpf/assets/68882678/6937223e-4742-42ca-8d7b-b9b99434eac9)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lmalenfant** [comment] 2024-05-30 21:11
When removing auto scale, the values selected must be within the current x, y min and max range. It is not possible to set them outside of those values.

There are some mouse and keyboard commands that control the view of the plot which might provide the desired effect.
![image](https://github.com/VirtualPhotonics/Vts.Gui.Wpf/assets/8517009/59db84bd-1921-4f9b-95ad-3e75ea2153cc)

**Comment by hayakawa16** [comment] 2024-05-31 01:17
I tried using the right mouse button and I can make the y-axis minimum be a 0 (this can be done even with Auto-Y checked).  However, the y-axis maximum gets modified as well so that I can't see first data point.  I'm not sure if zoom-out is possible on a laptop?

Wait, I figured it out.  Using two fingers on the mouse pad allows you to zoom in and out!

**Comment by lmalenfant** [comment] 2024-06-08 16:24
@vasangithub let me know if I can close this issue, it is not a bug but by design. If I don't hear back, I will close it at the end of the week.

If you think we need to change the functionality, we should create a feature request and write up the requirements.

**Closed** 2024-08-15 00:35 UTC
